### ISSUE TITLE
Lua errors with the newest Classic Era version

### ISSUE THREAD

**Issue by Pocokk** [pjeli/Tombstones#2]
Message: Interface/AddOns/Tombstones/Tombstones.lua:1383: CreateFrame(): Couldn't find inherited node "OptionsCheckButtonTemplate"
Time: Thu Nov 21 14:28:11 2024
Count: 1
Stack: Interface/AddOns/Tombstones/Tombstones.lua:1383: CreateFrame(): Couldn't find inherited node "OptionsCheckButtonTemplate"
[string "@Interface/AddOns/Tombstones/Tombstones.lua"]:1383: in function <Interface/AddOns/Tombstones/Tombstones.lua:1371>
[string "@Interface/AddOns/Tombstones/Tombstones.lua"]:4068: in function `?'
[string "@Interface/AddOns/Tombstones/Tombstones.lua"]:4094: in function <Interface/AddOns/Tombstones/Tombstones.lua:4093>

Locals: interPanel = TombstonesInterfaceOptions {
 name = "Tombstones"
}
titleText = FontString {
}
font = "Fonts\FRIZQT__.TTF"
_ = 11.999999
flags = ""
deathRecordsDB = <table> {
 useClassIcons = true
 showDanger = true
 targetDangerFramePos = <table> {
 }
 filteredTombsChat = true
 broadcastPvpDeath = true
 minimapDB = <table> {
 }
 rating = true
 TOMB_FILTERS = <table> {
 }
 autoSync = true
 dangerFrameUnlocked = true
 visiting = true
 showMarkers = true
 offerSync = true
 hide = false
 showZoneSplash = true
 reduceChatMsgs = false
 deathRecords = <table> {
 }
 zoneDangerFramePos = <table> {
 }
}
icon = <table> {
 callbacks = <table> {
 }
 radius = 5
 loggedIn = true
 tooltip = LibDBIconTooltip {
 }
 objects = <table> {
 }
 callbackRegistered = true
}
targetDangerFrame = nil
zoneDangerFrame = nil

and 

Message: Interface/AddOns/Tombstones/Engravings.lua:1089: CreateFrame(): Couldn't find inherited node "OptionsCheckButtonTemplate"
Time: Thu Nov 21 14:28:11 2024
Count: 1
Stack: Interface/AddOns/Tombstones/Engravings.lua:1089: CreateFrame(): Couldn't find inherited node "OptionsCheckButtonTemplate"
[string "@Interface/AddOns/Tombstones/Engravings.lua"]:1089: in function <Interface/AddOns/Tombstones/Engravings.lua:1076>
[string "@Interface/AddOns/Tombstones/Engravings.lua"]:2358: in function `?'
[string "@Interface/AddOns/Tombstones/Engravings.lua"]:2384: in function <Interface/AddOns/Tombstones/Engravings.lua:2383>

Locals: interPanel = EngravingsInterfaceOptions {
 name = "Engravings"
 parent = "Tombstones"
}
titleText = FontString {
}
font = "Fonts\FRIZQT__.TTF"
_ = 11.999999
flags = ""
engravingsDB = <table> {
 announcePlacement = true
 engravingRecords = <table> {
 }
 offerSync = false
 minimapDB = <table> {
 }
 participating = false
 reduceChatMsgs = false
 autoSync = true
 ENGR_FILTERS = <table> {
 }
}
icon = <table> {
 callbacks = <table> {
 }
 radius = 5
 loggedIn = true
 tooltip = LibDBIconTooltip {
 }
 objects = <table> {
 }
 callbackRegistered = true
}
hbdp = <table> {
 minimapPins = <table> {
 }
 worldmapPinsPool = <table> {
 }
 Minimap = Minimap {
 }
 worldmapPins = <table> {
 }
 worldmapProviderPin = <table> {
 }
 worldmapProvider = <table> {
 }
 updateFrame = Frame {
 }
 worldmapPinRegistry = <table> {
 }
 activeMinimapPins = <table> {
 }
 minimapPinRegistry = <table> {
 }
}

**Comment by pjeli** [comment]
This was fixed by https://github.com/pjeli/Tombstones/commit/fe95d1e7f4c91a2f1391236d6f8cf96ce4ad6d8b. Closing this for now. Additional changes to support DeathNotificationLib by yazpad also done. Sorry for the wait.
